---
- name: Include {{ ansible_system }} operation
  include: '{{ ansible_system }}.yml'

- name: Installation the Puppet agent.
  include: '{{ ansible_system }}/install.yml'
  when:
    - inventory_node_status is defined
    - not inventory_node_status.json.connected | bool
    - check_puppet_api.msg is not defined

- name: Puppet agent classification.
  include: '{{ ansible_system }}/classifie.yml'
  when:
#    - inventory_node_status is defined
#    - not inventory_node_status.json.connected | bool
#    - check_puppet_api.msg is not defined
