---
- name: Set puppet node group variables.
  set_fact:
    puppet_node_group: "{% if ansible_hostname.split('-')[2].lower() in node_region | lower %}{{ ansible_hostname.split('-')[3] }}{% else %}{{ ansible_hostname.split('-')[2] }}{% endif %}"
    puppet_node_env: "{% if ansible_hostname.split('-')[1].lower() == 'prd' %}production{% else %}development{% endif %}"

- name: Create a puppet node project group.
  uri:
    url: 'https://{{ puppet_master }}:{{ puppet_port.API }}/classifier-api/v1/groups'
    method: 'POST'
    force_basic_auth: 'yes'
    body: {"name": "{{ puppet_node_group }}", "environment": "{{ puppet_node_env }}","parent": "{% if ansible_hostname.split('-')[1] == 'prd' %}{{ puppet_environment_groups.production }}{% else %}{{ puppet_environment_groups.development }}{% endif %}", "classes": {}}
    body_format: 'json'
    validate_certs: 'no'
    headers:
      X-Authentication: '{{ token_status.json.token }}'
      X-Requested-By: '{{ ansible_default_ipv4.address }}'
      cache-control: 'no-cache'
  environment:
    no_proxy: '{{ puppet_master }}'
  register: node_group_status
  until: node_group_status.status == 303 or node_group_status.status == 422
  retries: 3
  delay: 3
  changed_when: false
  failed_when: false
  no_log: true

- name: Check the classifie group ID
  uri:
    url: 'https://{{ puppet_master }}:{{ puppet_port.API }}/classifier-api/v1/group-children/{% if ansible_hostname.split("-")[1] == "prd" %}{{ puppet_environment_groups.production }}{% else %}{{ puppet_environment_groups.development }}{% endif %}?depth=1'
    method: 'GET'
    status_code: '200'
    validate_certs: 'no'
    headers:
      X-Requested-By: '{{ ansible_default_ipv4.address }}'
      X-Authentication: '{{ token_status.json.token }}'
      cache-control: 'no-cache'
  environment:
    no_proxy: '{{ puppet_master }}'
  register: inventory_group_status
  until: inventory_group_status.status == 200
  retries: 3
  delay: 3
  changed_when: false
  failed_when: false
  no_log: true

- name: Set puppet node group ID.
  set_fact:
    puppet_node_group_id: '{{ inventory_group_status | json_query(query) }}'
  vars:
    query: "json[*].children[?name=='{{ puppet_node_group }}'].id"

- name: Pin puppet node to the group.
  uri:
    url: 'https://{{ puppet_master }}:{{ puppet_port.API }}/classifier-api/v1/groups/{{ item }}/pin'
    method: 'POST'
    force_basic_auth: 'yes'
    body: '{"nodes": ["{{ ansible_fqdn }}"]}'
    body_format: 'json'
    status_code: '204'
    validate_certs: 'no'
    headers:
      X-Authentication: '{{ token_status.json.token }}'
      X-Requested-By: '{{ ansible_default_ipv4.address }}'
      cache-control: 'no-cache'
  environment:
    no_proxy: '{{ puppet_master }}'
  register: node_pin_status
  until: node_pin_status.status == 204
  loop: '{{ puppet_node_group_id[0] }}'
  retries: 3
  delay: 3
  changed_when: false
  failed_when: false
  no_log: true
