---
- name: Download the puppet agent installation script.
  get_url:
    url: 'https://{{ puppet_compile }}:8140/packages/current/install.bash'
    dest: '{{ puppet_linux_tmp_path }}/puppet_agent_install.bash'
    owner: 'root'
    group: 'root'
    mode: '0644'
    validate_certs: 'no'
  environment:
    no_proxy: '{{ puppet_compile }}'

- name: Install agent with PE package management.
  shell: 'bash {{ puppet_linux_tmp_path }}/puppet_agent_install.bash'
  args:
    warn: 'no'
  environment:
    no_proxy: '{{ puppet_compile }}'

- name: Remove the puppet agent installation script.
  file:
    path: '{{ puppet_linux_tmp_path }}/puppet_agent_install.bash'
    state: 'absent'
